param([Parameter(Mandatory=$true)][string]$PackageDirectory,[Parameter(Mandatory=$true)][string]$RuntimeLog,[string]$ExpectedGitSha=$env:GITHUB_SHA)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$PackageDirectory=[IO.Path]::GetFullPath($PackageDirectory);$RuntimeLog=[IO.Path]::GetFullPath($RuntimeLog)
if(-not(Test-Path $RuntimeLog)){throw "Runtime log missing: $RuntimeLog"};$log=Get-Content -Raw $RuntimeLog
$smokePath=Join-Path $PackageDirectory 'RUNTIME_SMOKE.json';if(-not(Test-Path $smokePath)){throw 'RUNTIME_SMOKE.json missing.'};$smoke=Get-Content -Raw $smokePath|ConvertFrom-Json
$coreRequired=@('WORLD','HUD','TRAFFIC','NPC','MISSION','COMBAT','FIELDMASTER','FIELDMASTER_MOTION','FIELDMASTER_CONTROL','RATTLEBACK','RATTLEBACK_MOTION','RATTLEBACK_CONTROL','MULEBOX','MULEBOX_MOTION','MULEBOX_CONTROL','WANTED_COMPONENT','WANTED_ESCALATION','POLICE_RESPONSE','PURSUIT_ACTIVE','PURSUIT_CLOSING','ROADBLOCK_ACTIVE','INTERCEPTION_ACTIVE','ROADBLOCK_PHYSICAL_CROSSING','HANDLING_CONSEQUENCE','POST_SPIKE_ESCAPE','SAVE');$steps=@();$errors=@()
foreach($step in $coreRequired){$ok=$log -match ("DEMO_SCENARIO_STEP step="+[regex]::Escape($step)+" result=PASS");$steps+=[ordered]@{step=$step;passed=$ok};if(-not$ok){$errors+="missing scenario PASS: $step"}}
$crimeAction=$log -match 'DEMO_SCENARIO_ACTION action=INJECT_TEST_CRIME heat=130.0 target_wanted=4';if(-not$crimeAction){$errors+='deterministic wanted-4 crime action was not executed'}
$controlEvidence=@('Fieldmaster','Rattleback82','Mulebox1200')|ForEach-Object{$log -match ("DEMO_SCENARIO_CONTROL vehicle="+$_+" throttle=")};if($controlEvidence -contains $false){$errors+='native control telemetry incomplete'}
$pursuitEvidence=$log -match 'DEMO_SCENARIO_PURSUIT closing=PASS baseline_cm=';if(-not$pursuitEvidence){$errors+='pursuit did not prove measurable closing distance'}
$roadblockEvidence=$log -match 'DEMO_SCENARIO_ROADBLOCK active=PASS count=';if(-not$roadblockEvidence){$errors+='wanted-4 roadblock did not become active'}
$interceptionEvidence=$log -match 'DEMO_SCENARIO_INTERCEPTION active=PASS node=';if(-not$interceptionEvidence){$errors+='road-node interception did not become active'}
$nativeSpikeMatch=[regex]::Match($log,'ROADBLOCK_SPIKE_CONSEQUENCE vehicle=(Rattleback82|Mulebox1200) path=NATIVE_CHAOS tier=([0-9]+) hit=([0-9]+) tire_before=([0-9.]+) tire_after=([0-9.]+) tire_delta=([0-9.]+)')
$nativeSpikeEvidence=$nativeSpikeMatch.Success;$nativeSpikeVehicle='';$nativeSpikeBefore=0.0;$nativeSpikeAfter=0.0;$nativeSpikeDelta=0.0
if($nativeSpikeEvidence){$nativeSpikeVehicle=$nativeSpikeMatch.Groups[1].Value;$nativeSpikeBefore=[double]$nativeSpikeMatch.Groups[4].Value;$nativeSpikeAfter=[double]$nativeSpikeMatch.Groups[5].Value;$nativeSpikeDelta=[double]$nativeSpikeMatch.Groups[6].Value;if($nativeSpikeAfter -ge $nativeSpikeBefore -or $nativeSpikeDelta -le 0){$nativeSpikeEvidence=$false}}
if(-not$nativeSpikeEvidence){$errors+='no measurable Native Chaos spike-strip consequence was observed'}
$crossingMatch=[regex]::Match($log,'DEMO_SCENARIO_ROADBLOCK_CROSSING vehicle=(Rattleback82|Mulebox1200) result=PASS roadblock_hits=([0-9]+)');$physicalCrossing=$crossingMatch.Success;if(-not$physicalCrossing){$errors+='deterministic Native vehicle did not physically cross the active spike strip'}
$handlingMatch=[regex]::Match($log,'DEMO_SCENARIO_HANDLING_CONSEQUENCE vehicle=(Rattleback82|Mulebox1200) result=PASS tire_before=([0-9.]+) tire_after=([0-9.]+) wheel_risk_before=([0-9.]+) wheel_risk_after=([0-9.]+) throttle_limit_before=([0-9.]+) throttle_limit_after=([0-9.]+) steering_limit_before=([0-9.]+) steering_limit_after=([0-9.]+)')
$handlingEvidence=$handlingMatch.Success;$wheelRiskBefore=0.0;$wheelRiskAfter=0.0;$throttleBefore=1.0;$throttleAfter=1.0;$steeringBefore=1.0;$steeringAfter=1.0
if($handlingEvidence){$wheelRiskBefore=[double]$handlingMatch.Groups[4].Value;$wheelRiskAfter=[double]$handlingMatch.Groups[5].Value;$throttleBefore=[double]$handlingMatch.Groups[6].Value;$throttleAfter=[double]$handlingMatch.Groups[7].Value;$steeringBefore=[double]$handlingMatch.Groups[8].Value;$steeringAfter=[double]$handlingMatch.Groups[9].Value;if($wheelRiskAfter -le $wheelRiskBefore -or ($throttleAfter -ge $throttleBefore -and $steeringAfter -ge $steeringBefore)){$handlingEvidence=$false}}
if(-not$handlingEvidence){$errors+='Native handling consequence did not prove reduced control authority'}
$escapeMatch=[regex]::Match($log,'DEMO_SCENARIO_POST_SPIKE_ESCAPE vehicle=(Rattleback82|Mulebox1200) result=PASS duration=([0-9.]+) start_speed_cm_s=([0-9.]+) current_speed_cm_s=([0-9.]+) wheel_risk=([0-9.]+) throttle_limit=([0-9.]+) steering_limit=([0-9.]+)')
$postSpikeEscape=$escapeMatch.Success;if($postSpikeEscape){if([double]$escapeMatch.Groups[2].Value -lt 3.0 -or [double]$escapeMatch.Groups[4].Value -le 10.0){$postSpikeEscape=$false}}
if(-not$postSpikeEscape){$errors+='Native vehicle did not continue a measurable damaged escape after the spike strike'}
if($log -notmatch 'DEMO_SCENARIO_COMPLETE result=PASS steps=26'){$errors+='post-spike core scenario did not complete with 26-step PASS'}
$persistenceMatch=[regex]::Match($log,'DEMO_SCENARIO_DAMAGE_PERSISTENCE vehicle=(Rattleback82|Mulebox1200) result=PASS tire_saved=([0-9.]+) tire_reloaded=([0-9.]+) condition_saved=([0-9.]+) condition_reloaded=([0-9.]+)')
$damagePersistence=$persistenceMatch.Success;$persistedTire=0.0;$reloadedTire=0.0
if($damagePersistence){$persistedTire=[double]$persistenceMatch.Groups[2].Value;$reloadedTire=[double]$persistenceMatch.Groups[3].Value;if($persistedTire -ge 0.999 -or [math]::Abs($persistedTire-$reloadedTire) -gt 0.03){$damagePersistence=$false}}
if(-not$damagePersistence){$errors+='spike damage did not survive the SaveProgress/LoadProgress round-trip'}
$steps+=[ordered]@{step='DAMAGE_PERSISTENCE';passed=$damagePersistence}
$workshopMatch=[regex]::Match($log,'DEMO_SCENARIO_WORKSHOP_RECOVERY vehicle=(Rattleback82|Mulebox1200) result=PASS cash_before=([0-9]+) cash_after=([0-9]+) tire_before=([0-9.]+) tire_after=([0-9.]+) wheel_risk_before=([0-9.]+) wheel_risk_after=([0-9.]+) throttle_limit_before=([0-9.]+) throttle_limit_after=([0-9.]+) steering_limit_before=([0-9.]+) steering_limit_after=([0-9.]+)')
$workshopRecovery=$workshopMatch.Success;$workshopCashBefore=0;$workshopCashAfter=0;$repairedTire=0.0;$repairedRisk=0.0
if($workshopRecovery){$workshopCashBefore=[int]$workshopMatch.Groups[2].Value;$workshopCashAfter=[int]$workshopMatch.Groups[3].Value;$repairedTire=[double]$workshopMatch.Groups[5].Value;$repairedRisk=[double]$workshopMatch.Groups[7].Value;if($workshopCashAfter -ge $workshopCashBefore -or $repairedTire -lt 0.999){$workshopRecovery=$false}}
if(-not$workshopRecovery){$errors+='paid workshop did not restore persisted spike damage and handling'}
$steps+=[ordered]@{step='WORKSHOP_RECOVERY';passed=$workshopRecovery}
$damageRecoveryComplete=$log -match 'DEMO_SCENARIO_DAMAGE_RECOVERY result=PASS vehicle=(Rattleback82|Mulebox1200) route=spike-save-load-workshop';if(-not$damageRecoveryComplete){$errors+='damage recovery evidence subsystem did not complete'}
$structuralMatch=[regex]::Match($log,'DEMO_SCENARIO_STRUCTURAL_PERSISTENCE vehicle=(Rattleback82|Mulebox1200) result=PASS front_saved=([0-9.]+) front_reloaded=([0-9.]+) left_saved=([0-9.]+) left_reloaded=([0-9.]+) cooling_saved=([0-9.]+) cooling_reloaded=([0-9.]+) panel_mask_saved=([0-9]+) panel_mask_reloaded=([0-9]+) surcharge=([0-9]+)')
$structuralPersistence=$structuralMatch.Success;$structuralMask=0;$structuralCooling=0.0;$structuralSurcharge=0
if($structuralPersistence){$frontSaved=[double]$structuralMatch.Groups[2].Value;$frontReloaded=[double]$structuralMatch.Groups[3].Value;$leftSaved=[double]$structuralMatch.Groups[4].Value;$leftReloaded=[double]$structuralMatch.Groups[5].Value;$structuralCooling=[double]$structuralMatch.Groups[6].Value;$coolingReloaded=[double]$structuralMatch.Groups[7].Value;$structuralMask=[int]$structuralMatch.Groups[8].Value;$maskReloaded=[int]$structuralMatch.Groups[9].Value;$structuralSurcharge=[int]$structuralMatch.Groups[10].Value;if($frontSaved -ge 0.999 -or $leftSaved -ge 0.60 -or $structuralCooling -le 0.05 -or $structuralMask -le 0 -or $maskReloaded -ne $structuralMask -or $structuralSurcharge -le 0 -or [math]::Abs($frontSaved-$frontReloaded) -gt 0.03 -or [math]::Abs($leftSaved-$leftReloaded) -gt 0.03 -or [math]::Abs($structuralCooling-$coolingReloaded) -gt 0.03){$structuralPersistence=$false}}
if(-not$structuralPersistence){$errors+='structural zones/cooling/detached panel mask did not survive the v5 SaveProgress/LoadProgress round-trip'}
$steps+=[ordered]@{step='STRUCTURAL_PERSISTENCE';passed=$structuralPersistence}
$structuralRepairMatch=[regex]::Match($log,'DEMO_SCENARIO_STRUCTURAL_REPAIR vehicle=(Rattleback82|Mulebox1200) result=PASS cash_before=([0-9]+) cash_after=([0-9]+) paid=([0-9]+) surcharge_before=([0-9]+) panel_mask_before=([0-9]+) panel_mask_after=([0-9]+) body_min_after=([0-9.]+) cooling_after=([0-9.]+)')
$structuralRepair=$structuralRepairMatch.Success;$structuralPaid=0
if($structuralRepair){$cashBefore=[int]$structuralRepairMatch.Groups[2].Value;$cashAfter=[int]$structuralRepairMatch.Groups[3].Value;$structuralPaid=[int]$structuralRepairMatch.Groups[4].Value;$surchargeBefore=[int]$structuralRepairMatch.Groups[5].Value;$maskBefore=[int]$structuralRepairMatch.Groups[6].Value;$maskAfter=[int]$structuralRepairMatch.Groups[7].Value;$bodyMinAfter=[double]$structuralRepairMatch.Groups[8].Value;$coolingAfter=[double]$structuralRepairMatch.Groups[9].Value;if($cashAfter -ge $cashBefore -or $structuralPaid -le $surchargeBefore -or $surchargeBefore -le 0 -or $maskBefore -le 0 -or $maskAfter -ne 0 -or $bodyMinAfter -lt 0.999 -or $coolingAfter -gt 0.01){$structuralRepair=$false}}
if(-not$structuralRepair){$errors+='paid workshop did not restore persisted structural damage and charge the structural surcharge'}
$steps+=[ordered]@{step='STRUCTURAL_REPAIR';passed=$structuralRepair}
$structuralRecoveryComplete=$log -match 'DEMO_SCENARIO_STRUCTURAL_RECOVERY result=PASS vehicle=(Rattleback82|Mulebox1200) route=structural-save-load-workshop';if(-not$structuralRecoveryComplete){$errors+='structural damage recovery evidence subsystem did not complete'}

$structuralHandlingMatch=[regex]::Match($log,'DEMO_SCENARIO_STRUCTURAL_HANDLING vehicle=(Rattleback82|Mulebox1200) result=PASS severity=([0-9.]+) drag_rate=([0-9.]+) pull_rate=(-?[0-9.]+) power_retention=([0-9.]+) steering_retention=([0-9.]+) cooling=([0-9.]+) limp=YES front=([0-9.]+) right=([0-9.]+) panels=([0-9]+)')
$structuralHandling=$structuralHandlingMatch.Success;$structuralDriveSeverity=0.0;$structuralDriveDrag=0.0;$structuralDrivePull=0.0;$structuralDrivePower=1.0;$structuralDriveSteering=1.0
if($structuralHandling){$structuralDriveSeverity=[double]$structuralHandlingMatch.Groups[2].Value;$structuralDriveDrag=[double]$structuralHandlingMatch.Groups[3].Value;$structuralDrivePull=[double]$structuralHandlingMatch.Groups[4].Value;$structuralDrivePower=[double]$structuralHandlingMatch.Groups[5].Value;$structuralDriveSteering=[double]$structuralHandlingMatch.Groups[6].Value;if($structuralDriveSeverity -lt 0.30 -or $structuralDriveDrag -lt 0.28 -or [math]::Abs($structuralDrivePull) -lt 0.025 -or $structuralDrivePower -ge 0.90 -or $structuralDriveSteering -ge 0.94){$structuralHandling=$false}}
if(-not$structuralHandling){$errors+='structural damage did not produce measurable limp-home drag, asymmetric pull and control loss'}
$steps+=[ordered]@{step='STRUCTURAL_HANDLING';passed=$structuralHandling}

$structuralReloadMatch=[regex]::Match($log,'DEMO_SCENARIO_STRUCTURAL_RELOAD_HANDLING vehicle=(Rattleback82|Mulebox1200) result=PASS severity_before=([0-9.]+) severity_after=([0-9.]+) drag_before=([0-9.]+) drag_after=([0-9.]+) pull_before=(-?[0-9.]+) pull_after=(-?[0-9.]+) power_before=([0-9.]+) power_after=([0-9.]+) steering_before=([0-9.]+) steering_after=([0-9.]+) limp=YES')
$structuralReloadHandling=$structuralReloadMatch.Success
if($structuralReloadHandling){$pairs=@(@(2,3),@(4,5),@(6,7),@(8,9),@(10,11));foreach($pair in $pairs){if([math]::Abs([double]$structuralReloadMatch.Groups[$pair[0]].Value-[double]$structuralReloadMatch.Groups[$pair[1]].Value) -gt 0.06){$structuralReloadHandling=$false;break}}}
if(-not$structuralReloadHandling){$errors+='save/load did not reproduce the same structural drive consequence'}
$steps+=[ordered]@{step='STRUCTURAL_RELOAD_HANDLING';passed=$structuralReloadHandling}

$structuralDriveRecoveryMatch=[regex]::Match($log,'DEMO_SCENARIO_STRUCTURAL_DRIVE_RECOVERY vehicle=(Rattleback82|Mulebox1200) result=PASS cash_before=([0-9]+) cash_after=([0-9]+) paid=([0-9]+) severity_before=([0-9.]+) severity_after=([0-9.]+) drag_before=([0-9.]+) drag_after=([0-9.]+) pull_before=(-?[0-9.]+) pull_after=(-?[0-9.]+) power_after=([0-9.]+) steering_after=([0-9.]+) limp_after=NO')
$structuralDriveRecovery=$structuralDriveRecoveryMatch.Success;$structuralDrivePaid=0
if($structuralDriveRecovery){$cashBeforeDrive=[int]$structuralDriveRecoveryMatch.Groups[2].Value;$cashAfterDrive=[int]$structuralDriveRecoveryMatch.Groups[3].Value;$structuralDrivePaid=[int]$structuralDriveRecoveryMatch.Groups[4].Value;$severityAfter=[double]$structuralDriveRecoveryMatch.Groups[6].Value;$dragAfter=[double]$structuralDriveRecoveryMatch.Groups[8].Value;$pullAfter=[double]$structuralDriveRecoveryMatch.Groups[10].Value;$powerAfter=[double]$structuralDriveRecoveryMatch.Groups[11].Value;$steeringAfter=[double]$structuralDriveRecoveryMatch.Groups[12].Value;if($cashAfterDrive -ge $cashBeforeDrive -or $structuralDrivePaid -le 0 -or $severityAfter -gt 0.015 -or $dragAfter -gt 0.01 -or [math]::Abs($pullAfter) -gt 0.01 -or $powerAfter -lt 0.995 -or $steeringAfter -lt 0.995){$structuralDriveRecovery=$false}}
if(-not$structuralDriveRecovery){$errors+='paid workshop did not restore pristine structural driving behavior'}
$steps+=[ordered]@{step='STRUCTURAL_DRIVE_RECOVERY';passed=$structuralDriveRecovery}
$structuralDriveComplete=$log -match 'DEMO_SCENARIO_STRUCTURAL_DRIVE result=PASS vehicle=(Rattleback82|Mulebox1200) route=damage-physics-save-load-workshop';if(-not$structuralDriveComplete){$errors+='structural drive consequence evidence subsystem did not complete'}

if($ExpectedGitSha -and $smoke.git_sha -and $smoke.git_sha -ne $ExpectedGitSha){$errors+='scenario/runtime SHA mismatch'}
$result=if($errors.Count){'FAIL'}else{'PASS'}
$out=Join-Path $PackageDirectory 'DEMO_SCENARIO.json';[ordered]@{schema='gtt.demo-scenario.v11';game='Grand Theft Tractor';result=$result;git_sha=$smoke.git_sha;route='structural-limp-home-save-load-workshop-recovery';steps=$steps;required_step_count=33;core_step_count=$coreRequired.Count;crime_action_passed=$crimeAction;native_control_evidence=$controlEvidence;pursuit_closing_passed=$pursuitEvidence;roadblock_active_passed=$roadblockEvidence;interception_active_passed=$interceptionEvidence;native_spike_consequence_passed=$nativeSpikeEvidence;native_spike_vehicle=$nativeSpikeVehicle;native_spike_tire_before=$nativeSpikeBefore;native_spike_tire_after=$nativeSpikeAfter;native_spike_tire_delta=$nativeSpikeDelta;physical_crossing_passed=$physicalCrossing;handling_consequence_passed=$handlingEvidence;post_spike_escape_passed=$postSpikeEscape;damage_persistence_passed=$damagePersistence;persisted_tire_integrity=$persistedTire;reloaded_tire_integrity=$reloadedTire;workshop_recovery_passed=$workshopRecovery;workshop_cash_before=$workshopCashBefore;workshop_cash_after=$workshopCashAfter;repaired_tire_integrity=$repairedTire;repaired_wheel_risk=$repairedRisk;damage_recovery_complete=$damageRecoveryComplete;structural_persistence_passed=$structuralPersistence;structural_panel_mask=$structuralMask;structural_cooling_stress=$structuralCooling;structural_repair_surcharge=$structuralSurcharge;structural_repair_passed=$structuralRepair;structural_paid=$structuralPaid;structural_recovery_complete=$structuralRecoveryComplete;structural_handling_passed=$structuralHandling;structural_drive_severity=$structuralDriveSeverity;structural_drive_drag_rate=$structuralDriveDrag;structural_drive_pull_rate=$structuralDrivePull;structural_drive_power_retention=$structuralDrivePower;structural_drive_steering_retention=$structuralDriveSteering;structural_reload_handling_passed=$structuralReloadHandling;structural_drive_recovery_passed=$structuralDriveRecovery;structural_drive_paid=$structuralDrivePaid;structural_drive_complete=$structuralDriveComplete;wheel_risk_before=$wheelRiskBefore;wheel_risk_after=$wheelRiskAfter;throttle_limit_before=$throttleBefore;throttle_limit_after=$throttleAfter;steering_limit_before=$steeringBefore;steering_limit_after=$steeringAfter;errors=$errors;observed_utc=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json -Depth 6|Set-Content -Encoding UTF8 $out
Write-Host "[GTT] Structural limp-home + persistence + workshop recovery demo scenario: $result -> $out";if($errors.Count){throw ('Demo scenario failed: '+($errors -join '; '))}
