param([Parameter(Mandatory=$true)][string]$PackageDirectory,[Parameter(Mandatory=$true)][string]$RuntimeLog,[string]$ExpectedGitSha=$env:GITHUB_SHA)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$PackageDirectory=[IO.Path]::GetFullPath($PackageDirectory);$RuntimeLog=[IO.Path]::GetFullPath($RuntimeLog)
if(-not(Test-Path $RuntimeLog)){throw "Runtime log missing: $RuntimeLog"};$log=Get-Content -Raw $RuntimeLog
$smokePath=Join-Path $PackageDirectory 'RUNTIME_SMOKE.json';if(-not(Test-Path $smokePath)){throw 'RUNTIME_SMOKE.json missing.'};$smoke=Get-Content -Raw $smokePath|ConvertFrom-Json
$required=@('WORLD','HUD','TRAFFIC','NPC','MISSION','COMBAT','FIELDMASTER','FIELDMASTER_MOTION','FIELDMASTER_CONTROL','RATTLEBACK','RATTLEBACK_MOTION','RATTLEBACK_CONTROL','MULEBOX','MULEBOX_MOTION','MULEBOX_CONTROL','WANTED_COMPONENT','WANTED_ESCALATION','POLICE_RESPONSE','PURSUIT_ACTIVE','PURSUIT_CLOSING','ROADBLOCK_ACTIVE','INTERCEPTION_ACTIVE','ROADBLOCK_PHYSICAL_CROSSING','HANDLING_CONSEQUENCE','POST_SPIKE_ESCAPE','SAVE');$steps=@();$errors=@()
foreach($step in $required){$ok=$log -match ("DEMO_SCENARIO_STEP step="+[regex]::Escape($step)+" result=PASS");$steps+=[ordered]@{step=$step;passed=$ok};if(-not$ok){$errors+="missing scenario PASS: $step"}}
$crimeAction=$log -match 'DEMO_SCENARIO_ACTION action=INJECT_TEST_CRIME heat=130.0 target_wanted=4';if(-not$crimeAction){$errors+='deterministic wanted-4 crime action was not executed'}
$controlEvidence=@('Fieldmaster','Rattleback82','Mulebox1200')|ForEach-Object{$log -match ("DEMO_SCENARIO_CONTROL vehicle="+$_+" throttle=")};if($controlEvidence -contains $false){$errors+='native control telemetry incomplete'}
$pursuitEvidence=$log -match 'DEMO_SCENARIO_PURSUIT closing=PASS baseline_cm=';if(-not$pursuitEvidence){$errors+='pursuit did not prove measurable closing distance'}
$roadblockEvidence=$log -match 'DEMO_SCENARIO_ROADBLOCK active=PASS count=';if(-not$roadblockEvidence){$errors+='wanted-4 roadblock did not become active'}
$interceptionEvidence=$log -match 'DEMO_SCENARIO_INTERCEPTION active=PASS node=';if(-not$interceptionEvidence){$errors+='road-node interception did not become active'}
$nativeSpikeMatch=[regex]::Match($log,'ROADBLOCK_SPIKE_CONSEQUENCE vehicle=(Rattleback82|Mulebox1200) path=NATIVE_CHAOS tier=([0-9]+) hit=([0-9]+) tire_before=([0-9.]+) tire_after=([0-9.]+) tire_delta=([0-9.]+)')
$nativeSpikeEvidence=$nativeSpikeMatch.Success;$nativeSpikeVehicle='';$nativeSpikeBefore=0.0;$nativeSpikeAfter=0.0;$nativeSpikeDelta=0.0
if($nativeSpikeEvidence){$nativeSpikeVehicle=$nativeSpikeMatch.Groups[1].Value;$nativeSpikeBefore=[double]$nativeSpikeMatch.Groups[4].Value;$nativeSpikeAfter=[double]$nativeSpikeMatch.Groups[5].Value;$nativeSpikeDelta=[double]$nativeSpikeMatch.Groups[6].Value;if($nativeSpikeAfter -ge $nativeSpikeBefore -or $nativeSpikeDelta -le 0){$nativeSpikeEvidence=$false}}
if(-not$nativeSpikeEvidence){$errors+='no measurable Native Chaos spike-strip consequence was observed'}
$crossingMatch=[regex]::Match($log,'DEMO_SCENARIO_ROADBLOCK_CROSSING vehicle=(Rattleback82|Mulebox1200) result=PASS roadblock_hits=([0-9]+)');$physicalCrossing=$crossingMatch.Success;if(-not$physicalCrossing){$errors+='deterministic Native vehicle did not physically cross the active spike strip'}
$handlingMatch=[regex]::Match($log,'DEMO_SCENARIO_HANDLING_CONSEQUENCE vehicle=(Rattleback82|Mulebox1200) result=PASS tire_before=([0-9.]+) tire_after=([0-9.]+) wheel_risk_before=([0-9.]+) wheel_risk_after=([0-9.]+) throttle_limit_before=([0-9.]+) throttle_limit_after=([0-9.]+) steering_limit_before=([0-9.]+) steering_limit_after=([0-9.]+)')
$handlingEvidence=$handlingMatch.Success;$wheelRiskBefore=0.0;$wheelRiskAfter=0.0;$throttleBefore=1.0;$throttleAfter=1.0;$steeringBefore=1.0;$steeringAfter=1.0
if($handlingEvidence){$wheelRiskBefore=[double]$handlingMatch.Groups[4].Value;$wheelRiskAfter=[double]$handlingMatch.Groups[5].Value;$throttleBefore=[double]$handlingMatch.Groups[6].Value;$throttleAfter=[double]$handlingMatch.Groups[7].Value;$steeringBefore=[double]$handlingMatch.Groups[8].Value;$steeringAfter=[double]$handlingMatch.Groups[9].Value;if($wheelRiskAfter -le $wheelRiskBefore -or ($throttleAfter -ge $throttleBefore -and $steeringAfter -ge $steeringBefore)){$handlingEvidence=$false}}
if(-not$handlingEvidence){$errors+='Native handling consequence did not prove reduced control authority'}
$escapeMatch=[regex]::Match($log,'DEMO_SCENARIO_POST_SPIKE_ESCAPE vehicle=(Rattleback82|Mulebox1200) result=PASS duration=([0-9.]+) start_speed_cm_s=([0-9.]+) current_speed_cm_s=([0-9.]+) wheel_risk=([0-9.]+) throttle_limit=([0-9.]+) steering_limit=([0-9.]+)')
$postSpikeEscape=$escapeMatch.Success;if($postSpikeEscape){if([double]$escapeMatch.Groups[2].Value -lt 3.0 -or [double]$escapeMatch.Groups[4].Value -le 10.0){$postSpikeEscape=$false}}
if(-not$postSpikeEscape){$errors+='Native vehicle did not continue a measurable damaged escape after the spike strike'}
if($log -notmatch 'DEMO_SCENARIO_COMPLETE result=PASS steps=26'){$errors+='post-spike escape scenario did not complete with 26-step PASS'}
if($ExpectedGitSha -and $smoke.git_sha -and $smoke.git_sha -ne $ExpectedGitSha){$errors+='scenario/runtime SHA mismatch'}
$result=if($errors.Count){'FAIL'}else{'PASS'}
$out=Join-Path $PackageDirectory 'DEMO_SCENARIO.json';[ordered]@{schema='gtt.demo-scenario.v8';game='Grand Theft Tractor';result=$result;git_sha=$smoke.git_sha;route='post-spike-escape-dynamics';steps=$steps;required_step_count=$required.Count;crime_action_passed=$crimeAction;native_control_evidence=$controlEvidence;pursuit_closing_passed=$pursuitEvidence;roadblock_active_passed=$roadblockEvidence;interception_active_passed=$interceptionEvidence;native_spike_consequence_passed=$nativeSpikeEvidence;native_spike_vehicle=$nativeSpikeVehicle;native_spike_tire_before=$nativeSpikeBefore;native_spike_tire_after=$nativeSpikeAfter;native_spike_tire_delta=$nativeSpikeDelta;physical_crossing_passed=$physicalCrossing;handling_consequence_passed=$handlingEvidence;post_spike_escape_passed=$postSpikeEscape;wheel_risk_before=$wheelRiskBefore;wheel_risk_after=$wheelRiskAfter;throttle_limit_before=$throttleBefore;throttle_limit_after=$throttleAfter;steering_limit_before=$steeringBefore;steering_limit_after=$steeringAfter;errors=$errors;observed_utc=(Get-Date).ToUniversalTime().ToString('o')}|ConvertTo-Json -Depth 6|Set-Content -Encoding UTF8 $out
Write-Host "[GTT] Post-spike escape dynamics demo scenario: $result -> $out";if($errors.Count){throw ('Demo scenario failed: '+($errors -join '; '))}
