param([Parameter(Mandatory=$true)][string]$PackageDirectory,[Parameter(Mandatory=$true)][string]$RuntimeLog,[string]$ExpectedGitSha=$env:GITHUB_SHA,[switch]$RequireVisual)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest;$PackageDirectory=[IO.Path]::GetFullPath($PackageDirectory);$RuntimeLog=[IO.Path]::GetFullPath($RuntimeLog)
$buildPath=Join-Path $PackageDirectory 'BUILD_INFO.json';$smokePath=Join-Path $PackageDirectory 'RUNTIME_SMOKE.json';$scenarioPath=Join-Path $PackageDirectory 'DEMO_SCENARIO.json';$gameplayPath=Join-Path $PackageDirectory 'GAMEPLAY_SMOKE.json';$fieldmasterPath=Join-Path $PackageDirectory 'FIELDMASTER_CHAOS_TELEMETRY.json'
foreach($p in @($buildPath,$smokePath,$scenarioPath,$gameplayPath,$fieldmasterPath,$RuntimeLog)){if(-not(Test-Path $p)){throw "Required demo evidence missing: $p"}}
$build=Get-Content -Raw $buildPath|ConvertFrom-Json;$smoke=Get-Content -Raw $smokePath|ConvertFrom-Json;$scenario=Get-Content -Raw $scenarioPath|ConvertFrom-Json;$gameplay=Get-Content -Raw $gameplayPath|ConvertFrom-Json;$fieldmaster=Get-Content -Raw $fieldmasterPath|ConvertFrom-Json;$log=Get-Content -Raw $RuntimeLog
if($smoke.result -ne 'PASS'){throw 'Packaged runtime smoke did not PASS.'};if($scenario.result -ne 'PASS'){throw 'Deterministic demo scenario did not PASS.'};if($gameplay.result -ne 'PASS'){throw 'Packaged gameplay smoke did not PASS.'};if($build.platform -ne 'Win64'){throw 'Build evidence is not Win64.'}
if($fieldmaster.schema -ne 'gtt.fieldmaster-chaos-telemetry.v1' -or $fieldmaster.result -ne 'PASS'){throw 'Fieldmaster Native Chaos telemetry did not PASS.'};foreach($field in @('dedicated_movement','drivetrain','authored_wheels','suspension_runtime')){if($fieldmaster.$field -ne 'PASS'){throw "Fieldmaster telemetry acceptance missing PASS: $field"}}
if([int]$fieldmaster.sample_count -lt 3 -or [int]$fieldmaster.driven_sample_count -lt 1 -or [int]$fieldmaster.grounded_sample_count -lt 1 -or [int]$fieldmaster.torque_sample_count -lt 1){throw 'Fieldmaster telemetry manifest lacks minimum runtime observations.'}
if($scenario.schema -ne 'gtt.demo-scenario.v11'){throw "Demo scenario schema mismatch: $($scenario.schema)"};if([int]$scenario.required_step_count -ne 33 -or $scenario.steps.Count -ne 33){throw 'Demo scenario does not contain the complete 33-step 0.0.94 evidence route.'}
foreach($field in @('structural_handling_passed','structural_reload_handling_passed','structural_drive_recovery_passed','structural_drive_complete')){if(-not $scenario.$field){throw "Demo scenario missing required structural limp-home PASS: $field"}}
if($ExpectedGitSha -and $ExpectedGitSha -ne 'unknown' -and $build.git_sha -ne $ExpectedGitSha){throw "Build SHA mismatch: package=$($build.git_sha), expected=$ExpectedGitSha"};foreach($e in @($scenario,$gameplay,$fieldmaster)){if($e.git_sha -and $ExpectedGitSha -and $e.git_sha -ne $ExpectedGitSha){throw 'Runtime evidence SHA mismatch.'}}
$vehicles=@('Fieldmaster','Rattleback82','Mulebox1200');$missing=@();foreach($vehicle in $vehicles){if($log -notmatch "NATIVE_CHAOS_SMOKE_READY.*vehicle=$vehicle"){$missing+=$vehicle}};if($missing.Count){throw "Native Chaos packaged evidence missing for: $($missing -join ', ')"}
$recoveryStatus='NOT_REQUIRED_FOR_VERSION';if($build.version -eq '0.0.96'){$recoveryPath=Join-Path $PackageDirectory 'RECOVERY_CHOICE.json';if(-not(Test-Path $recoveryPath)){throw 'RECOVERY_CHOICE.json missing for 0.0.96.'};$recovery=Get-Content -Raw $recoveryPath|ConvertFrom-Json;if($recovery.schema -ne 'gtt.recovery-choice.v1' -or $recovery.result -ne 'PASS'){throw '0.0.96 recovery choice evidence did not PASS.'};foreach($field in @('offer_passed','manual_choice_passed','tow_preserves_damage_passed','separate_repair_passed','route_complete')){if(-not $recovery.$field){throw "0.0.96 recovery evidence missing PASS: $field"}};if($recovery.git_sha -and $ExpectedGitSha -and $recovery.git_sha -ne $ExpectedGitSha){throw 'Recovery choice evidence SHA mismatch.'};$recoveryStatus='PASS'}
$visualPath=Join-Path $PackageDirectory 'DEMO_VISUAL_ACCEPTANCE.json';$visualStatus='NOT_REQUIRED_FOR_TECHNICAL_GATE';if($RequireVisual){if(-not(Test-Path $visualPath)){throw 'DEMO_VISUAL_ACCEPTANCE.json missing.'};$visual=Get-Content -Raw $visualPath|ConvertFrom-Json;if($visual.result -ne 'PASS' -or -not $visual.reviewer -or -not $visual.reviewed_utc){throw 'Visual acceptance is incomplete.'};$visualStatus='PASS'}
$evidence=[ordered]@{schema=4;game='Grand Theft Tractor';result='PASS';git_sha=$build.git_sha;version=$build.version;platform=$build.platform;runtime_smoke='PASS';deterministic_demo_scenario='PASS';scenario_schema=$scenario.schema;scenario_steps=$scenario.steps;structural_limp_home='PASS';player_selectable_recovery=$recoveryStatus;packaged_gameplay_smoke='PASS';native_chaos_smoke_ready=$vehicles;fieldmaster_native_chaos_telemetry='PASS';fieldmaster_telemetry_schema=$fieldmaster.schema;fieldmaster_telemetry_samples=$fieldmaster.sample_count;visual_acceptance=$visualStatus;evaluated_utc=(Get-Date).ToUniversalTime().ToString('o')};$evidence|ConvertTo-Json -Depth 8|Set-Content -Encoding UTF8 (Join-Path $PackageDirectory 'DEMO_TECHNICAL_GATE.json');Write-Host "[GTT] Demo technical evidence gate: PASS (scenario v11 / 33 steps / Fieldmaster Chaos telemetry / structural limp-home / recovery=$recoveryStatus)"
