param([Parameter(Mandatory=$true)][string]$PackageDirectory,[Parameter(Mandatory=$true)][string]$RuntimeLog,[string]$ExpectedGitSha=$env:GITHUB_SHA,[switch]$RequireVisual)
$ErrorActionPreference='Stop'; Set-StrictMode -Version Latest
$PackageDirectory=[IO.Path]::GetFullPath($PackageDirectory); $RuntimeLog=[IO.Path]::GetFullPath($RuntimeLog)
$buildPath=Join-Path $PackageDirectory 'BUILD_INFO.json'; $smokePath=Join-Path $PackageDirectory 'RUNTIME_SMOKE.json'; $gameplayPath=Join-Path $PackageDirectory 'GAMEPLAY_SMOKE.json'
foreach($p in @($buildPath,$smokePath,$gameplayPath,$RuntimeLog)){if(-not(Test-Path $p)){throw "Required demo evidence missing: $p"}}
$build=Get-Content -Raw $buildPath|ConvertFrom-Json; $smoke=Get-Content -Raw $smokePath|ConvertFrom-Json; $gameplay=Get-Content -Raw $gameplayPath|ConvertFrom-Json; $log=Get-Content -Raw $RuntimeLog
if($smoke.result -ne 'PASS'){throw 'Packaged runtime smoke did not PASS.'}; if($gameplay.result -ne 'PASS'){throw 'Packaged gameplay smoke did not PASS.'}; if($build.platform -ne 'Win64'){throw 'Build evidence is not Win64.'}
if($ExpectedGitSha -and $ExpectedGitSha -ne 'unknown' -and $build.git_sha -ne $ExpectedGitSha){throw "Build SHA mismatch: package=$($build.git_sha), expected=$ExpectedGitSha"}
if($gameplay.git_sha -and $ExpectedGitSha -and $gameplay.git_sha -ne $ExpectedGitSha){throw 'Gameplay smoke SHA mismatch.'}
$vehicles=@('Fieldmaster','Rattleback82','Mulebox1200'); $missing=@(); foreach($vehicle in $vehicles){if($log -notmatch "NATIVE_CHAOS_SMOKE_READY.*vehicle=$vehicle"){$missing+=$vehicle}}; if($missing.Count){throw "Native Chaos packaged evidence missing for: $($missing -join ', ')"}
$visualPath=Join-Path $PackageDirectory 'DEMO_VISUAL_ACCEPTANCE.json'; $visualStatus='NOT_REQUIRED_FOR_TECHNICAL_GATE'; if($RequireVisual){if(-not(Test-Path $visualPath)){throw 'DEMO_VISUAL_ACCEPTANCE.json missing.'}; $visual=Get-Content -Raw $visualPath|ConvertFrom-Json; if($visual.result -ne 'PASS' -or -not $visual.reviewer -or -not $visual.reviewed_utc){throw 'Visual acceptance is incomplete.'}; $visualStatus='PASS'}
$evidence=[ordered]@{schema=2;game='Grand Theft Tractor';result='PASS';git_sha=$build.git_sha;version=$build.version;platform=$build.platform;runtime_smoke='PASS';packaged_gameplay_smoke='PASS';native_chaos_smoke_ready=$vehicles;representative_coverage=$gameplay.representative_coverage;visual_acceptance=$visualStatus;evaluated_utc=(Get-Date).ToUniversalTime().ToString('o')}
$out=Join-Path $PackageDirectory 'DEMO_TECHNICAL_GATE.json'; $evidence|ConvertTo-Json -Depth 6|Set-Content -Encoding UTF8 $out; Write-Host '[GTT] Demo technical evidence gate: PASS'
