#!/usr/bin/env python3
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]
gate=(ROOT/'Scripts/evaluate_demo_candidate.ps1').read_text(encoding='utf-8');workflow=(ROOT/'.github/workflows/win64-package-evidence.yml').read_text(encoding='utf-8');release_verify=(ROOT/'Scripts/verify_release_pipeline.py').read_text(encoding='utf-8');roadmap=(ROOT/'Docs/ROADMAP.md').read_text(encoding='utf-8');playtest=(ROOT/'Docs/PLAYTEST_0.0.94.md').read_text(encoding='utf-8');changelog=(ROOT/'CHANGELOG.d/0.0.94.md').read_text(encoding='utf-8')
for token in ('BUILD_INFO.json','RUNTIME_SMOKE.json','DEMO_SCENARIO.json','NATIVE_CHAOS_RUNTIME.json',"scenario.result -ne 'PASS'","native.result -ne 'PASS'",'ExpectedGitSha','Fieldmaster','Rattleback82','Mulebox1200','NATIVE_CHAOS_SMOKE_READY','gtt.native-chaos-runtime.v1','native_chaos_runtime','DEMO_TECHNICAL_GATE.json','DEMO_VISUAL_ACCEPTANCE.json','RequireVisual',"scenario.schema -ne 'gtt.demo-scenario.v11'",'required_step_count -ne 33','structural_handling_passed','structural_reload_handling_passed','structural_drive_recovery_passed','structural_drive_complete','structural_limp_home'):assert token in gate,f'missing demo evidence gate token: {token}'
# 0.0.94 introduced technical-gate schema 5. Later milestones add evidence manifests and increment
# the schema, so verify the historical floor instead of requiring a stale literal.
schema_match=re.search(r'(?m)^\s*schema=(\d+)\s*$',gate);assert schema_match and int(schema_match.group(1))>=5,f'demo technical gate schema regressed below 0.0.94 schema-5 floor: {schema_match.group(1) if schema_match else "missing"}'
for token in ('runs-on: [self-hosted, windows, x64, unreal-5.8]','evaluate_demo_scenario.ps1','evaluate_native_chaos_runtime.ps1','evaluate_demo_candidate.ps1','DEMO_SCENARIO.json','NATIVE_CHAOS_RUNTIME.json','DEMO_TECHNICAL_GATE.json','GTT_RUNTIME.log','actions/upload-artifact@v4'):assert token in workflow,f'missing Win64 candidate workflow token: {token}'
# 0.1.14 established the first complete candidate-label contract. Future additive evidence milestones
# may advance the version while all of the original technical gates remain mandatory.
version_match=re.search(r"default:\s*'([0-9]+)\.([0-9]+)\.([0-9]+)'",workflow);assert version_match,'Win64 candidate workflow default version is not parseable';candidate_tuple=tuple(int(version_match.group(i)) for i in range(1,4));assert candidate_tuple>=(0,1,14),f'Win64 candidate version regressed below 0.1.14: {".".join(version_match.groups())}';candidate_version='.'.join(version_match.groups())
runtime_match=re.search(r'-MinimumAliveSeconds\s+(\d+)\s+-LaunchTimeoutSeconds\s+(\d+)',workflow);assert runtime_match,'Win64 candidate workflow smoke lifetime/timeout is not parseable';minimum_alive=int(runtime_match.group(1));launch_timeout=int(runtime_match.group(2));assert minimum_alive>=125,f'Win64 candidate runtime regressed below 125 seconds: {minimum_alive}';assert launch_timeout>minimum_alive,f'Win64 candidate launch timeout must exceed minimum alive time: {launch_timeout}<={minimum_alive}'
assert 'verify_demo_candidate_gate.py' in release_verify;assert '0.0.94' in playtest and '0.0.94' in changelog
for token in ('<!-- SWIR-ROADMAP-STANDARD:v1 -->','## 📊 Overall progress','ROADMAP-96.2%25','DONE-125%2F130','███████████████████░ 96.2%'):assert token in roadmap,f'roadmap Style Lock/progress mismatch: {token}'
checks=re.findall(r'^- \[[x ]\] ',roadmap,flags=re.MULTILINE);done=len(re.findall(r'^- \[x\] ',roadmap,flags=re.MULTILINE));assert len(checks)==130 and done==125
assert '- [ ] Full Win64 CI/build runner' in roadmap and '- [ ] Full Unreal compile + packaged Win64 smoke test' in roadmap
scenario=(ROOT/'Scripts/evaluate_demo_scenario.ps1').read_text(encoding='utf-8')
for token in ('ROADBLOCK_SPIKE_CONSEQUENCE','NATIVE_CHAOS','tire_before','tire_after','tire_delta','gtt.demo-scenario.v11','physical_crossing_passed','wheel_risk_after','POST_SPIKE_ESCAPE','damage_persistence_passed','workshop_recovery_passed','structural_persistence_passed','structural_repair_passed','structural_handling_passed','structural_reload_handling_passed','structural_drive_recovery_passed','structural_drive_complete','required_step_count=33'):assert token in scenario,f'missing 0.0.94 structural limp-home evidence token: {token}'
print(f'[OK] Win64 Native structural limp-home + native telemetry candidate gate verified; scenario v11/33 hard-bound; additive technical schema={schema_match.group(1)}; candidate={candidate_version}; runtime window={minimum_alive}/{launch_timeout}s; roadmap 125/130.')